version: '3.1'
name: api-project

services:
  app: 
    build:
      context: . 
      args:
        - JWT_PASSWORD=PLlQjpCEDA1JaZOfj7X8
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/app 
      - /usr/app/node_modules
    networks:
      - networkName 
    depends_on:
      - database
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '8080:3306'
    expose:
      - '3306'
    volumes:
      - my-sql:/var/lib/mysql
    networks:
      - networkName 
    hostname: database
volumes:
  my-sql:
networks:
  networkName: